### ISSUE TITLE
.repo/manifest.xml refer to same repos which are not access-able  publicly

### ISSUE THREAD

**Issue by azuwis** [ParanoidAndroid/paranoid#1]
Follow the guild at https://github.com/ParanoidAndroid/paranoid, but meet some problem:

```
Fetching projects:  98% (304/310)  Permission denied (publickey).
fatal: The remote end hung up unexpectedly
```

It seem like https://github.com/ParanoidAndroid/android/blob/jellybean/default.xml contain some private repos.

**Comment by ParanoidAndroid** [comment]
Yes, frameworks are still private and will be private for a while
